# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "app" do |app|
    app.vm.box = "chef/centos-6.5"

    app.vm.hostname = "app"

    app.vm.network "private_network", ip: "192.168.34.10"

    app.ssh.forward_agent = true

    app.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    app.vm.provision "shell", path: "scripts/bootstrap.sh"

    app.vm.provision "ansible" do |ansible|
      ansible.groups = {
        "webservers" => [ "app" ],
        "devtools" => [ "app" ],
        "exports" => [ "app" ]
      }

      ansible.playbook = "ansible/site.yml"

      ansible.extra_vars = { ansible_ssh_user: "vagrant" }
      ansible.sudo = true;
    end
  end
end
