#!/bin/bash

DIR_REMOTE=/opt/photos
DIR_LOCAL=`dirname $0`/export/photos
mkdir -p $DIR_LOCAL

DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
case "$DIST_OS" in
    'sunos')
        DIST_OS="solaris"
        ;;
    'hp-ux' | 'hp-ux64')
        DIST_OS="hpux"
        ;;
    'darwin')
        DIST_OS="macosx"
        ;;
    'unix_sv')
        DIST_OS="unixware"
        ;;
esac

if [ "$DIST_OS" = "macosx" ]; then
  sudo mount -t nfs -o soft,intr,rsize=8192,wsize=8192,timeo=900,retrans=3,proto=tcp,rw 192.168.35.10:$DIR_REMOTE $DIR_LOCAL
else
  which showmount >/dev/null || true
  [ "$?" -ne "0" ] && sudo apt-get install -y nfs-common
  sudo mount -t nfs -o proto=tcp 192.168.35.10:$DIR_REMOTE $DIR_LOCAL
fi

exit 0
