---
- name: Install nginx
  yum: name=nginx state=present

- name: Ensure nginx starts on boot
  service: name=nginx state=started enabled=yes

- name: Ensure default.conf absent
  file: dest=/etc/nginx/conf.d/default.conf state=absent
  notify: Reload nginx

- name: Create web root
  file: path=/var/www state=directory owner=root group=nginx mode=2755
