- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: configure and deploy mongodb
  hosts: mongo
  remote_user: root

  roles:
    - mongo

- name: configure and deploy api
  hosts: photos_api
  remote_user: root

  roles:
    - photos_api

- name: configure and deploy process
  hosts: photos_process
  remote_user: root

  roles:
    - photos_process

- name: configure and deploy web
  hosts: photos_web
  remote_user: root

  roles:
    - photos_web
