#!/bin/bash

set -x

SHORTNAME=$1

DATABASE=my_ami_$SHORTNAME
USER=ami_$SHORTNAME
PASSWORD=password

SOURCE_DIR=/var/www

sed -i -e "s/ENGINE=InnoDB/ENGINE=TokuDB/g" $SOURCE_DIR/$SHORTNAME.sql

mysql --user="$USER" --password="$PASSWORD" --execute="DROP DATABASE $DATABASE; CREATE DATABASE $DATABASE default character set utf8 default collate utf8_general_ci; use $DATABASE; SET storage_engine=TOKUDB; source $SOURCE_DIR/$SHORTNAME.sql;"

exit 0

